### ISSUE TITLE
Enhancements/Fixes For Next Version

### ISSUE THREAD

**Issue by R0BC0D3R** [nerva-project/nerva-gui#1]
- Make upgrade process easier
- Make check for updates allow user to automatically upgrade

**Comment by R0BC0D3R** [comment]
- By default use 50% of threads for mining.
- Allow to change mining threads in main UI (maybe)

**Comment by R0BC0D3R** [comment]
- When popup is open and it's over main application and user clicks to another application, popup goes out of focus so you cannot use application.

**Comment by R0BC0D3R** [comment]
- Test if --quicksync works

**Comment by old-greywolf** [comment]
export_transfers is a good tool to have, which is in the cli version but not the gui.  maybe include it as a menu option under Wallet.

**Comment by R0BC0D3R** [comment]
All those improvements are now part of version 0.3.2.0
